version: '3.1'

services:
    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 1420:1420
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: mymicds-staging
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: passtherootword
        ports:
            - 27017:27017
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: passtherootword
            ME_CONFIG_MONGODB_URL: mongodb://root:passtherootword@mongo:27017/
        depends_on:
            - mongo
