export var styleList = {
    waves: {
        navbar: {
            StyleUrl: '../css/navbar/Waves.css',
            TemplateUrl: '../templates/navbar/waves.html'},
        planner: {
            StyleUrl: '../css/plannerContent/Waves.css',
            TemplateUrl: '../templates/plannerContent/waves.html'},
        progress: {
            StyleUrl: '../css/mainContent/progress/Waves.progress.css',
            TemplateUrl: '../templates/mainContent/progress/waves.progress.html'},
        background: {
            JSUrl: '../Backgrounds/Waves/Waves.js',
            HTMLUrl: '../Backgrounds/Waves/Waves.html',
            StyleUrl: '../Backgrounds/Waves/Waves.css',
            LibUrl: ''},
        lunch: {
            StyleUrl: '../css/lunchContent/Waves.css',
            TemplateUrl: '../templates/lunchContent/waves.html'},
        main: {
            StyleUrl: '../css/mainContent/Waves.css',
            TemplateUrl: '../templates/mainContent/waves.html'},
        account: {
            StyleUrl: '../css/accountContent/Waves.css',
            TemplateUrl: '../templates/accountContent/waves.html'},
        profile: {
            StyleUrl: '../css/profileContent/Waves.css',
            TemplateUrl: '../templates/profileContent/waves.html'}
    },
    default: {
        navbar: {
            StyleUrl: '../css/navbar/default.css',
            TemplateUrl: '../templates/navbar/default.html'},
        planner: {
            StyleUrl: '../css/plannerContent/default.css',
            TemplateUrl: '../templates/plannerContent/default.html'},
        progress: {
            StyleUrl: '../css/mainContent/progress/default.progress.css',
            TemplateUrl: '../templates/mainContent/progress/default.progress.html'},
        background: {
            JSUrl: '../Backgrounds/default/default.js',
            HTMLUrl: '../Backgrounds/default/default.html',
            StyleUrl: '../Backgrounds/default/default.css',
            LibUrl: ''},
        lunch: {
            StyleUrl: '../css/lunchContent/default.css',
            TemplateUrl: '../templates/lunchContent/default.html'},
        main: {
            StyleUrl: '../css/mainContent/default.css',
            TemplateUrl: '../templates/mainContent/default.html'},
        account: {
            StyleUrl: '../css/accountContent/default.css',
            TemplateUrl: '../templates/accountContent/default.html'},
        profile: {
            StyleUrl: '../css/profileContent/default.css',
            TemplateUrl: '../templates/profileContent/default.html'}
    },
};
